---
R1:
  hostname: "192.168.31.101"
  username: "john"
  password: "cisco"
  port: 830
  groups:
    - cisco_group

R2:
  hostname: "192.168.31.102"
  username: "john"
  password: "cisco"
  port: 830
  groups:
    - cisco_group

R3:
  hostname: "192.168.31.103"
  username: "john"
  password: "cisco"
  port: 830
  groups:
    - cisco_group
